name: RPN Calculator Auto-Grader

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    # 1. GitHub deposundaki kodlari sanal makineye cek
    - name: Depoyu Cek (Checkout)
      uses: actions/checkout@v4

    # 2. Python ortamini hazirla
    - name: Python Kurulumu
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # 3. C# (Mono) ortamini hazirla
    - name: C# (Mono) Kurulumu
      run: |
        sudo apt-get update
        sudo apt-get install -y mono-complete

    # 4. Testleri Calistir
    - name: Testleri Baslat
      run: python3 lab50-v6.py tests
