name: RPN Calculator Auto-Grader

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Depoyu Cek (Checkout)
      uses: actions/checkout@v4

    - name: Python Kurulumu
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: C# (Mono) Kurulumu
      run: |
        sudo apt-get update
        sudo apt-get install -y mono-complete

    - name: Test Dosyasini Indir ve Baslat
      run: |
        mkdir -p tests
        # Senin Gist linkinden g√ºncel testi indiriyoruz:
        wget -O tests/__init__.py https://gist.githubusercontent.com/Aleynasimsek/a58a16fa2adfbbbde27e907574ed0fbb/raw/0d3ebc3dd7e8375f740e757fef3bf759bc73495c/__init__.py
        python3 lab50-v6.py tests
